language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - yarn test:prod && yarn build
after_success:
  - yarn example:build
  - yarn example:deploy
  - yarn semantic-release
